USE [master]
GO

/****** Object:  Database [ContractorTimeCheck]    Script Date: 18/03/2018 12:51:47 ******/
CREATE DATABASE [ContractorTimeCheck]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ContractorTimeCheck', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATAContractorTimeCheck.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ContractorTimeCheck_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATAContractorTimeCheck_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ContractorTimeCheck] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ContractorTimeCheck].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ContractorTimeCheck] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ContractorTimeCheck] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ContractorTimeCheck] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ContractorTimeCheck] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ContractorTimeCheck] SET ARITHABORT OFF 
GO

ALTER DATABASE [ContractorTimeCheck] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ContractorTimeCheck] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ContractorTimeCheck] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ContractorTimeCheck] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ContractorTimeCheck] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ContractorTimeCheck] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ContractorTimeCheck] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ContractorTimeCheck] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ContractorTimeCheck] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ContractorTimeCheck] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ContractorTimeCheck] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ContractorTimeCheck] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ContractorTimeCheck] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ContractorTimeCheck] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ContractorTimeCheck] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ContractorTimeCheck] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ContractorTimeCheck] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ContractorTimeCheck] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ContractorTimeCheck] SET  MULTI_USER 
GO

ALTER DATABASE [ContractorTimeCheck] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ContractorTimeCheck] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ContractorTimeCheck] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ContractorTimeCheck] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ContractorTimeCheck] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ContractorTimeCheck] SET  READ_WRITE 
GO


